/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IIconsTelegram: typeof import('~icons/icons/telegram')['default']
    IIconsYoutube: typeof import('~icons/icons/youtube')['default']
    ITablerArrowBackUp: typeof import('~icons/tabler/arrow-back-up')['default']
    ITablerArrowForwardUp: typeof import('~icons/tabler/arrow-forward-up')['default']
    ITablerBrandX: typeof import('~icons/tabler/brand-x')['default']
    ITablerChevronLeft: typeof import('~icons/tabler/chevron-left')['default']
    ITablerChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    ITablerClipboard: typeof import('~icons/tabler/clipboard')['default']
    ITablerEyeOff: typeof import('~icons/tabler/eye-off')['default']
    ITablerGripVertical: typeof import('~icons/tabler/grip-vertical')['default']
    ITablerPencil: typeof import('~icons/tabler/pencil')['default']
    ITablerPhoto: typeof import('~icons/tabler/photo')['default']
    ITablerPin: typeof import('~icons/tabler/pin')['default']
    ITablerPlayerPlay: typeof import('~icons/tabler/player-play')['default']
    ITablerPlus: typeof import('~icons/tabler/plus')['default']
    ITablerTrash: typeof import('~icons/tabler/trash')['default']
    ITablerX: typeof import('~icons/tabler/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
