/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ITablerArrowBackUp: typeof import('~icons/tabler/arrow-back-up')['default']
    ITablerArrowForwardUp: typeof import('~icons/tabler/arrow-forward-up')['default']
    ITablerArrowsDiagonal: typeof import('~icons/tabler/arrows-diagonal')['default']
    ITablerChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    ITablerExpand: typeof import('~icons/tabler/expand')['default']
    ITablerGrip: typeof import('~icons/tabler/grip')['default']
    ITablerGripVertical: typeof import('~icons/tabler/grip-vertical')['default']
    ITablerPencil: typeof import('~icons/tabler/pencil')['default']
    ITablerPlus: typeof import('~icons/tabler/plus')['default']
    ITablerX: typeof import('~icons/tabler/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
